expt:
  delay: 10
  delay_sigma: 0.1
  duration: 30
  num_values: 5
  stim_length: 1
  stim_sigma: 0
  stim_start_max: 5
  stim_start_min: 2
  type: review_task
  value_max: 10
  value_min: 1
model:
  activation: relu
  bias: true
  dt: 0.01
  hidden_size: 100
  input_size: 6
  output_size: 1
  sigma_in: 0.01
  sigma_re: 0.01
  tau_distribution: uniform
  tau_effect: all
  tau_max: 15
  tau_min: 1
  type: expirimental_RNN
training:
  batch_size: 50
  early_stopping_loss: 0.001
  epochs: 1000
  learning_rate: 0.001
  save_path: best_model.pth
  size: 1000
  valid_split:
  - 0.85
  - 0.15
