expt:
  kernel_tau: 0.1
  type: integration_task
model:
  activation: tanh
  bias: true
  dt: 0.01
  hidden_size: 100
  input_size: 1
  name: expirimental_RNN
  output_size: 1
  rank: unconstrained
  sigma_in: 0.01
  sigma_re: 0.01
  tau_distribution: uniform
  tau_effect: all
  tau_groups:
  - 1
  tau_max: 1.9
  tau_min: 0.1
  tau_proportions:
  - 1
  type: expirimental_RNN
training:
  batch_size: 50
  early_stopping_loss: 0.001
  epochs: 1000
  learning_rate: 0.001
  save_path: best_model.pth
  size: 1000
  valid_split:
  - 0.85
  - 0.15
