model:
  type: 'expirimental_RNN'
  input_size: 6
  hidden_size: 100
  output_size: 1
  tau_distribution: 'bimodal_normal'
  tau_min: 1
  tau_max: 15
  tau_change: 8
  tau_mean1: 4
  tau_mean2: 12
  tau_std1: 1
  tau_std2: 1
  tau_proportions: [0.5, 0.5]
  tau_effect: 'decay'
  dt: 0.01
  activation: 'relu'
  bias: True
  sigma_in: 0.01
  sigma_re: 0.01

training:
  valid_split: [0.85, 0.15]
  batch_size: 50
  learning_rate: 0.001
  epochs: 1000
  save_path: 'best_model.pth'
  early_stopping_loss: 0.001
  size: 1000

expt:
  type: 'review_task'
  num_values: 5
  stim_start_min: 2
  stim_start_max: 5
  stim_length: 1
  value_min: 1
  value_max: 10
  delay: 10
  delay_sigma: 0.1
  stim_sigma: 0
  duration: 30

