model:
  type: 'EI_RNN'
  input_size: 2
  hidden_size: 100
  output_size: 1
  tau: 1
  dt: 0.01
  activation: 'relu'
  bias: True
  sigma_in: 0.05
  sigma_re: 0.01
  eprop: 0.8

training:
  valid_split: [0.85, 0.15]
  batch_size: 50
  learning_rate: 0.001
  epochs: 1000
  save_path: 'best_model.pth'
  early_stopping_loss: 0.005
  mask_loss: False
  grad_clip: 
  size: 1000

expt:
  type: 'PC'
  symmetric: False
  stim_start_min: 2
  stim_start_max: 5
  num_cohs: 5
  coh_radius: 0.1
  duration: 20