model:
  type: 'MultiTauRNN'
  input_size: 2
  hidden_size: 100
  output_size: 1
  tau_distribution: 'groups'
  tau_groups: [1, 10]
  tau_proportions: [0.5, 0.5]
  dt: 0.01
  activation: 'relu'
  bias: True
  sigma_in: 0.01
  sigma_re: 0.01

training:
  valid_split: [0.85, 0.15]
  batch_size: 50
  learning_rate: 0.001
  epochs: 1000
  save_path: 'best_model.pth'
  early_stopping_loss: 0.001
  size: 1000

expt:
  type: 'PC'
  symmetric: False
  stim_start_min: 2
  stim_start_max: 5
  num_cohs: 5
  coh_radius: 0.15
  duration: 20