model:
  type: 'RNN'
  input_size: 1
  hidden_size: 100
  output_size: 1
  tau: 1
  dt: 0.01
  activation: 'relu'
  bias: True
  sigma_in: 0.01
  sigma_re: 0.01

training:
  valid_split: [0.85, 0.15]
  batch_size: 50
  learning_rate: 0.001
  epocs: 1000
  save_path: 'best_model.pth'
  early_stopping_loss: 0.001
  size: 1000

expt:
  type: 'instant_DM'
  stim_start_min: 5
  stim_start_max: 10
  stim_length: 1
  decision_length: 2
  sigma_length: 1
  duration: 20